import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>To Do App</title>
        <link rel="icon" href="/favicon.ico" />
        {/* Other head elements can be added here */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
